---
title: "Final Project"
author: "Grace Montgomery"
subtitle: MGSC 410 Problem Set Template
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}
library(knitr)
# As long as you are working in a Rstudio Project file, you shouldn't need to 'hard code' directories like this 
# change to your own working directory
# knitr::opts_knit$set(root.dir = 'C:/Users/hersh/Dropbox/Chapman/Teaching/MGSC_310/Fall_2019/problem_sets')
# setwd('C:/Users/hersh/Dropbox/Chapman/Teaching/MGSC_310/Fall_2019/problem_sets')

# set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# general rchunk code options

# this sets text to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = TRUE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               fig.width = 5,  
               fig.height = 4,
               fig.align='center')


```

## Loading Libraries

```{r}
rm(list = ls())
```

```{r}
library('magrittr')
library('dplyr')
library('tidyr')
library('tidyverse')
library('ggridges')
library('gganimate')
library('forcats')
library('rsample')
library('glmnet')
library('glmnetUtils')
library('broom')
library('coefplot')
library('cluster')
library('factoextra')
library('NbClust')

```

# More libraries 
```{r}


```

na.strings = c("foo", "bar")

Loading datasets

```{r}
app_activity <- read.csv(here::here("cleaned_data", "app_activity.csv"))
master_data <- read.csv(here::here("cleaned_data", "master_data.csv"), na.strings = "NULL")
```

Data Manipulation
#changed Purchase.Amount.In.USD to a numeric in excel and replaced the $- to 0
```{r}
master_data <- master_data %>% mutate(
  Purchase.Amount.in.USD = as.numeric(Purchase.Amount.in.USD),
  Langauge = as.factor(Language),
  Subscription.Type = as.factor(Subscription.Type),
  Subscription.Event.Type = as.factor(Subscription.Event.Type),
  Purchase.Store = as.factor(Purchase.Store),
  Currency = as.factor(Currency),
  Demo.User = as.factor(Demo.User),
  Free.Trial.User = as.factor(Free.Trial.User),
  Auto.Renew = as.factor(Auto.Renew),
  Country = as.factor(Country),
  User.Type = as.factor(User.Type),
  Lead.Platform = as.factor(Lead.Platform),
  Email.Subscriber = as.factor(Email.Subscriber),
  Push.Notifications = as.factor(Push.Notifications)
  ) %>% select(-Purchase.Amount)


# change "unknown" in Lead platform to NA


```

#First attempt cluster unsupervised
Understanding the subscriber segments present in the database
Unsupervised 
Cluster by country
gaussian mixture model

```{r}
# determine number of clusters using elbow method
fviz_nbclust(master_data, 
             kmeans, 
             method = "wss") +
  geom_vline(xintercept = 4, 
             linetype = 2)+
  labs(subtitle = "Elbow method")


# # determine number of clusters using Gap Statistic method
# fviz_nbclust(Customers_DF, 
#              kmeans, 
#              nstart = 25,  
#              method = "gap_stat", 
#              nboot = 500) +
#  labs(subtitle = 
#         "Gap statistic method")
# 
# 
# # install.packages('NbClust')
# 
# # determine number of clusters using Gap Statistic method
# Nb_cl <- NbClust(Customers_DF, 
#         diss = NULL, 
#         distance = "euclidean",
#         min.nc = 2, 
#         max.nc = 15, 
#         method = "kmeans")
# 
# Nb_cl$Best.nc[1,]
```




```{r}
#---------------------------------------------------------------------------------
# K-Means Clustering Using Optimal Number of Clusters Learned Above
#---------------------------------------------------------------------------------
# centers = 3 is number of clusters
kmeans3 <- kmeans(Customers_DF, 
                  centers = 3, 
                  nstart = 25)

kmeans3$centers

#---------------------------------------------------------------------------------
# Plot Clusters Using Clust Plot
#---------------------------------------------------------------------------------
clusplot(Customers_DF, 
         kmeans3$cluster, 
         color=TRUE, 
         shade=FALSE,
         labels=5, lines=2)
```


























